spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: ${DATABASE_PLATFORM}
        show-sql: false
        hibernate:
            ddl-auto: update
server:
    port: 9001
springdoc:
    version: "@org.springdoc.version@"
    api-docs:
        enabled: false
    swagger-ui:
        path: /swagger-ui