spring:
  profiles:
    active: "@spring.profiles.active@"
database:
    config:
        url: ${DATABASE_URL}
        driverClassname: ${DRIVER_CLASSNAME}
        username: ${DATABASE_URL}
        password: ${DATABASE_PASSWORD}
server:
    port: 9001
springdoc:
    version: "@org.springdoc.version@"
    swagger-ui:
        path: /swagger-ui